contentDir = "content"
publishDir = "public"

baseURL = "https://yjwang39.github.io/momento/"
title = "Momento"
theme = "lanyon"

languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.RData", "\\.gz$"]
canonifyurls = true
relativeURLs = true
paginate = 10  # Number of items per page in paginated lists.
rssLimit = 100
timeout = 10000
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
hasCJKLanguage = true


[permalinks]
post = ":year/:month/:day/:title/"
fixed = ":title/"

[params]
author = "Yujuan Wang"
title = "Momento"
tagline = 'some quick reference'
description = 'A place to gather useful information I keep on forgetting.'
year = "2020 Yujuan Wang"
copyright = "&copy; {year}, All Rights Reserved."
DateForm = "2006/01/02"
mainSections = "post"

[params.github]
url = "https://github.com/yjwang39/momento"

# Configure the Markdown renderer.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[taxonomies]
tag = "tags"
category = "categories"
